//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCLAB {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class hclab : global::System.Configuration.ApplicationSettingsBase {
        
        private static hclab defaultInstance = ((hclab)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new hclab())));
        
        public static hclab Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=10.10.11.10)(PORT=1521))(CO" +
            "NNECT_DATA=(SERVICE_NAME=hclab))); user id = hclab; password = hclab;")]
        public string WES {
            get {
                return ((string)(this["WES"]));
            }
            set {
                this["WES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=10.20.5.10)(PORT=1521))(CON" +
            "NECT_DATA=(SERVICE_NAME=hclab))) ; user id = hclab; password = hclab;")]
        public string NAGA {
            get {
                return ((string)(this["NAGA"]));
            }
            set {
                this["NAGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=192.171.12.100)(PORT=1521))" +
            "(CONNECT_DATA=(SERVICE_NAME=hclab))); user id = hclab; password = hclab;")]
        public string TABUNOK {
            get {
                return ((string)(this["TABUNOK"]));
            }
            set {
                this["TABUNOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=192.171.51.100)(PORT=1521))" +
            "(CONNECT_DATA=(SERVICE_NAME=hclab))); user id = hclab; password = hclab;")]
        public string LILOAN {
            get {
                return ((string)(this["LILOAN"]));
            }
            set {
                this["LILOAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=192.171.10.100)(PORT=1521))" +
            "(CONNECT_DATA=(SERVICE_NAME=hclab))); user id = hclab; password = hclab;")]
        public string DIAMOND {
            get {
                return ((string)(this["DIAMOND"]));
            }
            set {
                this["DIAMOND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=192.171.21.100)(PORT=1521))" +
            "(CONNECT_DATA=(SERVICE_NAME=hclab))); user id = hclab; password = hclab;")]
        public string MACTAN {
            get {
                return ((string)(this["MACTAN"]));
            }
            set {
                this["MACTAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=10.62.2.10)(PORT=1521))(CON" +
            "NECT_DATA=(SERVICE_NAME=hclab))); user id = hclab; password = hclab;")]
        public string CONSOLACION {
            get {
                return ((string)(this["CONSOLACION"]));
            }
            set {
                this["CONSOLACION"] = value;
            }
        }
    }
}
